### PR TITLE
Add GHC 9 support

### PR DESCRIPTION
**Pull request by brandonchinn178**

### CODE REVIEW

**Comment by brandonchinn178** [comment]
@georgefst it might be nice to make all CI jobs required when merging into `master`. As admin, you can always override the requirement in an emergency

**Comment by brandonchinn178** [comment]
blocked on https://github.com/tweag/ormolu/issues/688

**Comment by brandonchinn178** [comment]
@georgefst it seems like ormolu hasn't been merged into fourmolu for almost a year (nov 2020). is there a process or script for merging upstream changes (e.g. https://github.com/fourmolu/fourmolu/pull/40)? or is it just manual cherry picking?

**Comment by brandonchinn178** [comment]
Superceded by https://github.com/fourmolu/fourmolu/pull/106

**Comment by georgefst** [comment]
> is there a process or script for merging upstream changes (e.g. #40)? or is it just manual cherry picking?

It's just painstaking manual cherry-picking, unfortunately. Thanks for doing it!

The good news is that Ormolu development has slowed down hugely since around the time we forked last summer. It's mostly very stable now.

**Pull request closed without merging**
