### PR TITLE
Fix indentation in multiline tuple patterns

### PR DESCRIPTION
**Pull request by brandonchinn178**
This formatting behavior was discovered in https://github.com/fourmolu/fourmolu/issues/400. It's partially an issue in Ormolu (https://github.com/tweag/ormolu/pull/1101), but it's more egregious with leading commas.

Hold off on merging this until https://github.com/tweag/ormolu/pull/1101 is resolved; if it's accepted upstream, we can hold off on this and rebase after merging Ormolu in

### CODE REVIEW

**Comment by arybczak** [comment]
Ugh, I didn't realize this layout doesn't work in `case` patterns :disappointed: This sucks.

**Comment by arybczak** [comment]
Any news about this? I see the `ormolu` PR has stalled :(

**Comment by brandonchinn178** [comment]
I bumped the other thread, we'll see if they respond soon

**Comment by brandonchinn178** [comment]
Found a better, simpler solution here: https://github.com/fourmolu/fourmolu/pull/418

**Pull request closed without merging**
