### PR TITLE
Only apply indentation hack for indentation > 2

### PR DESCRIPTION
**Pull request by brandonchinn178**
We have logic in `inci` to round down to the closest multiple of the indentation before increasing the indentation, in the case of parenthesized expressions, which shift the indentation off the indentation column.

```hs
-- Ormolu behavior:
( Maybe
    Int -> -- <- 'Int' is one indentation (2 spaces) from the column 'Maybe' starts on
  String
)

-- If Fourmolu just naively changed indentation to 4:
( Maybe
      Int -> -- <- 'Int' is one indentation (4 spaces) from the column 'Maybe' starts on,
  String     -- but it now starts on column 6, because of the "( ", so all subsequent
)            -- newlines will be off the indentation column

-- Fourmolu's behavior today, rounding down (indentation=4):
( Maybe
    Int -> -- <- The start of 'Maybe' is on column 2, so we round down to a multiple
  String   -- of 4 (0), then increase the indentation to 4
)
```

This hack works when the parentheses starts on the indentation column, but can cause odd formatting when the parentheses starts off the indentation column (https://github.com/fourmolu/fourmolu/issues/428)

```hs
-- Ormolu behavior:
something
  <> ( foo
         bar -- <- 'bar' is one indentation (2 spaces) from the start of 'foo', but 'bar'
         baz -- and 'baz' are now on an odd column, due to being shifted 5 characters
     )       -- due to "<> ( "

-- Fourmolu behavior today, rounding down (indentation=2):
something
  <> ( foo
        bar -- <- 'bar' is now only 1 space from 'foo' to keep it on the indentation column,
        baz -- which is different from what Ormolu does at 2 space indentation
     )
```

So we'll hack the hack by only applying the hack if indentation > 2. A better solution might involve something like tracking the current indentation separately from the next indentation level, but I don't want to think about that right now

### CODE REVIEW

**Comment by brandonchinn178** [comment]
@Kleidukos This changes quite a few lines in the Cabal codebase, but IMO it's an improvement to the formatting. What do you think? Would you prefer this be gated behind an option?

**Comment by Kleidukos** [comment]
@geekosaur can I let you check this out? :heart_hands:

**Comment by ulysses4ever** [comment]
It'd be easier to opine if the three paragraphs of the PR description were accompanied by an example. 

Cabal still uses fourmolu 0.12 so I don't see how it could affect it. One day it should move on though. It'd be great if changes in new versions of fourmolu were guarded by flags always (apologies if this is already the case but I think it wasn't always the case in the past). Opt in or opt out is a judgement call of course. But there should be a way to move to a newer version without reformating the whole code base. And that way should be explained in release notes...

**Comment by geekosaur** [comment]
Looks fine to me. (Note: as I read it, 1-space indents have been expanded to 2-space, because the leading "+" or "-" is " " for unchanged lines. This makes diffs readable _unless_ they're of tab-indented lines.)

**Comment by brandonchinn178** [comment]
@ulysses4ever Thanks for the comment, I updated the PR description with examples.

On one hand, I agree, people wanting to upgrade GHC will need to upgrade fourmolu, and it'd be annoying to have to include reformatting the codebase in order to upgrade GHC version. On the other, maintaining flags to maintain backwards compatibility in perpetuity doesn't sound like a fun time (this particular instance is fairly small, but speaking generally).

What do you think about some policy like:
* All backwards incompatible changes should be opt-out
* Flag is guaranteed to exist for at least one version of Fourmolu that supports GHC X.Y+1
* When flag is used, Fourmolu shows warning to migrate
* Fourmolu is free to remove flag if flag was introduced in the previous GHC version

**Comment by ulysses4ever** [comment]
Thank you Brandon for engaging. Couple points.

1. I would welcome any policy if there's none currently. I think anything formal will be an improvement.
2. I don't use fourmolu enough to have a good intuition about precise terms.
3. The proposal you put seems to lean conservative esp. concerning updates for newer GHCs and dropping those flags,  but this is fine because it's your call and also see (1) above...

The issue with cabal is that big swings in output of newer fourmolu's invalidate a lot of PRs, and we always have a good bunch open ones... Given that cabal has to follow GHC pretty closely, the policy you propose doesn't give us a ton of time to adjust (if we want to update fourmolu regularly). It's half a year that takes GHC X.Y+1 to release normally (I hope I got it right?) worst case (and I know that GHC releases get delayed all the time but if we need a number...).

**Comment by brandonchinn178** [comment]
That's a good point. What frequency would Cabal be open to reformatting the codebase? Once a year? I'd be happy to make it "remove a flag after GHC X.Y+1 or 1 year, whichever comes later"

**Comment by brandonchinn178** [comment]
I'll already be at that meeting, for a different reason 😁

How often does Cabal need to update what version of GHC it builds with? You can't stay pinned on 0.12 if you need to upgrade the version of GHC that builds fourmolu, or if cabal uses newer syntax.

If that's not an issue, then I think we can go back to just the GHC X.Y+1 policy.

**Comment by Mikolaj** [comment]
I'm inclined to haggle to make it less common than once a year. :) But let's find a compromise.

**Comment by Kleidukos** [comment]
@brandonchinn178 see you in 5 minutes then :)

**Comment by brandonchinn178** [comment]
Per the newly merged breaking changes policy, I'm tempted to merge this in. The current implementation violates the policy:

> It will always be possible to replicate Ormolu's formatting with a suitable `fourmolu.yaml`

So this one-time breaking change would make us consistent with Ormolu again

**Comment by georgefst** [comment]
Very nice! We should have done this years ago.

I was never very happy with #37. No coincidence that it stems from the period when there was no one around to review my code...

**Pull request merged**
