### PR TITLE
Fixes for function arrows

### PR DESCRIPTION
**Pull request by brandonchinn178**
Found some edge cases for function arrows, and was able to simplify the code without the `PrevTypeCtx` machinery.

Some of the changes I made seem to still pass tests (e.g. moving things in/out of a `located` block). If we find a regression or issue later, we can fix it later with an added test

### CODE REVIEW

**Comment by brandonchinn178** [comment]
cc @3kyro

**Comment by 3kyro** [comment]
@brandonchinn178 There seems to be a regression on multi line arguments with interleaved comments. You can test the following:

````haskell
withComments
  -- Comment
  :: Int
  -- Comment
  -> Int
  -- Comment
  -> Int
```` 
which gets formatted as:
````haskell
withComments
    :: -- Comment
    Int
    -> -- Comment
    Int
    -> -- Comment
    Int
````

**Comment by brandonchinn178** [comment]
@3kyro thanks! The situation isn't much better on `main`, so it's not too much of a regression
```hs
foo
    :: -- asdf
    Int
    -- bar
    -> Bool
```
But I'll take a look!

**Comment by 3kyro** [comment]
> The situation isn't much better on main

Indeed it's not 😞 

Apart from this, the fixes look like a big improvement and I didn't notice any other formatting change regarding leading function arrows.

**Comment by brandonchinn178** [comment]
@3kyro just pushed 3 new commits! should have the comments fixed, and i also found an issue with leading arrows + explicit type signatures for expressions

**Pull request merged**
