### PR TITLE
Add version of `git ls-files` command which avoids length limits

### PR DESCRIPTION
**Pull request by georgefst**
Changed my mind as soon as I hit merge on https://github.com/fourmolu/fourmolu/pull/263.

Credit to @clintonmead.

### CODE REVIEW

**Review by brandonchinn178 — APPROVED** [review]
The comment doesn't quite highlight correctly with `console`. Try `bash` perhaps?

**Comment by georgefst** [comment]
Eugh, thanks. Does `console` even do anything useful? I'd have expected it to highlight the prompt or something.

**Comment by georgefst** [comment]
Actually, in VSCode it does nicely de-emphasise the `$`. But no difference on GitHub. What a mess.

**Comment by brandonchinn178** [comment]
Console is good for showing REPL output; anything not prefixed with `$` or `>>>` or something gets colored blue (or vice versa or something)

**Pull request merged**
