### PR TITLE
Leading arrows

### PR DESCRIPTION
**Pull request by expipiplus1**
This adds a --leading-arrows option and closes https://github.com/fourmolu/fourmolu/issues/86

~~It's currently on top of my alignment branch for my convenience, I don't
think it should be that hard to extract though~~

I've extracted it from on top of my align work, although it's a more convenient for me to have it on there. I'll be keeping that up to date on this branch (joe-align-leading) https://github.com/expipiplus1/fourmolu/tree/joe-align-leading

CC @dpwiz

### CODE REVIEW

**Comment by expipiplus1** [comment]
TODO

`data/examples/declaration/class/default-signatures-four-out.hs`

```diff
-    bar ::
-        String ->
-        String ->
-        a
+    bar
+        :: String
+        -> String
+        -> a
```

Putting `::` on the next line from `bar` looks weird (same for a few other tests including `data/examples/declaration/data/field-layout/gadt-four-out.hs`)

GADTs sometimes look weird.

Should data/examples/declaration/value/function/typed-expressions-four-out.hs have an indented `::` 

in: 
```haskell
foo x = x::Int
bar x = Just x ::
  Maybe String
```

out:
```haskell
foo x = x :: Int
bar x =
    Just x
    :: Maybe String
```

**Comment by expipiplus1** [comment]
OK, I've fixed the GADT weirdness, for some reason in Ormolu the existing rendering for GADTs duplicated lots of work from p_hsType

**Comment by expipiplus1** [comment]
Upstream PR for some changes: https://github.com/tweag/ormolu/pull/711/files

**Comment by dpwiz** [comment]
You're awesome and your dog is awesome!

**Comment by expipiplus1** [comment]
image

**Comment by arybczak** [comment]
Hey. What is the status of this PR? It would be great to have this in fourmolu as "hanging arrows" is not the style I've seen anyone use when writing code without a formatter.

**Comment by expipiplus1** [comment]
> Hey. What is the status of this PR? It would be great to have this in fourmolu as "hanging arrows" is not the style I've seen anyone use when writing code without a formatter.

Probably depends on https://github.com/fourmolu/fourmolu/issues/49

**Comment by brandonchinn178** [comment]
👋 @expipiplus1 
Thank you for opening this PR and being patient while we sorted out how to handle all the new contributions for new configuration options!

If you haven't noticed, we finally merged in a new testing framework for configuration options ([#169](https://github.com/fourmolu/fourmolu/pull/169))! This means we can finally address the backlog of open PRs.

Please do the following steps

- [ ] Rebase against `main`

    ```bash
    git remote add upstream git@github.com:fourmolu/fourmolu
    git fetch upstream
    git rebase -i upstream/main
    ```

- [ ] Resolve merge conflicts
- [ ] Ensure `CHANGELOG.md` has been updated
- [ ] Ensure configuration docs in `README.md` have been updated
- [ ] Ensure `fourmolu.yaml` updated to stay in sync with config in `README.md`
- [ ] Ensure tests have been added

You can use [#135](https://github.com/fourmolu/fourmolu/pull/135) as a reference for this checklist.

**Comment by expipiplus1** [comment]
I did see that! Very exciting.

No chance I'll be able to get to this before July, but I'm happy for
someone else to take over before then. I'll hopefully find time in July or
later otherwise.

**Comment by 3kyro** [comment]
@expipiplus1 I can try rebasing your branch and adding tests if you don't mind.

**Comment by expipiplus1** [comment]
That would be great :)

**Comment by brandonchinn178** [comment]
Closing in favor of https://github.com/fourmolu/fourmolu/pull/209

**Pull request closed without merging**
