### PR TITLE
Add Circle CI

### LINKED ISSUE #11: Setup some CI
Travis is easy and familiar to me but maybe it's a good time to try Circle CI

### PR DESCRIPTION
**Pull request by brandonchinn178**
Fixes #11 

In order to test this, @parsonsmatt you'll need to set up this project on Circle CI

### CODE REVIEW

**Comment by brandonchinn178** [comment]
@parsonsmatt are you still interested in trying out Circle CI for this? I could also try to use GitHub actions instead, if you'd like

**Comment by parsonsmatt** [comment]
I've found the GH Actions to be a bit annoying with the `persistent` and `esqueleto` repos, so I'd be happy to give Circle CI a shot.

**Comment by parsonsmatt** [comment]
Maybe I should transfer this repo to an organization, so it's not tied to my account directly. I'm not active on it, for the most part.

**Comment by brandonchinn178** [comment]
That makes sense. What organization would this be transferred to? And who would be the repo admins? (Only a repo admin can set up Circle CI for a project)

**Comment by parsonsmatt** [comment]
We can doa  `fourmolu` organization, and I'd be happy to make @georgefst and you admins.

**Comment by brandonchinn178** [comment]
Sounds good to me!

**Comment by brandonchinn178** [comment]
@parsonsmatt any update on setting up a `fourmolu` organization?

**Comment by parsonsmatt** [comment]
It is done 😎

**Comment by brandonchinn178** [comment]
@parsonsmatt sorry, I might need a few more actions from you, as the owner of the Fourmolu organization. You should have gotten an email asking for access from the CircleCI github app. Can you approve that?

Later, I might also need you to change some things on the "Settings" tab for this repo (e.g. to make Circle CI checks required for PRs)

**Comment by parsonsmatt** [comment]
No worries! I approved the application. Let me know if there's anything else I can do. Thanks for all your work in setting this up!

**Comment by brandonchinn178** [comment]
Can you go to this link and click "Set up project"?

https://app.circleci.com/projects/project-dashboard/github/fourmolu/

Click "use existing `.circleci/config.yml` file", which doesn't exist on the `master` branch, so it'll fail at first. Then if you can go to the settings page and click something like "allow forks to start CI"

**Comment by parsonsmatt** [comment]
Done. I checked this box: 
image

**Comment by brandonchinn178** [comment]
@georgefst I'm getting an error: `fourmolu.cabal` claims that `fourmolu` works for
```cabal
        HsYAML >=0.1.1.3 && <0.3,
        HsYAML-aeson >=0.1 && <0.3,
```
But `fourmolu` actually fails to compile for `HsYAML < 0.2` (`Data.Yaml` does not export `Pos`, and `Data.Yaml.decode` returns `Either String [v]`) and `HsYAML-aeson < 0.2` (`Data.Yaml.Aeson.decode1` also returns `Either String v` without `Pos`, same as `Data.Yaml.decode`).

Couple options here, not sure which is preferred:
1. Bump lower bounds of each to `0.2`
2. Remove `Pos` from `ConfigParseError` (it's currently unused anyway)
3. Make the second argument in `ConfigParseError` match the `Left` type in `decode1`
4. Add bogus `Pos` type + value if needed

Options 2-4 all require `-XCPP` in at least one location.

**Comment by georgefst** [comment]
Ah, I should have been more careful there. I think just bump the lower bound - `0.2` has been out for two years.

**Comment by brandonchinn178** [comment]
@georgefst oh 🤦 my bad, I tried loosening the bounds for GHC 8.6. Apparently the original lower bounds were intentional

**Comment by brandonchinn178** [comment]
@georgefst This should be ready for review!

**Comment by expipiplus1** [comment]
One massive downside to CircleCI is that it requires users to have a CircleCI account to even see build logs from PRs. IMO this is quite a deterrent to contributions.

**Pull request merged**
