### PR TITLE
Generate PrinterOpts definitions without TH

### PR DESCRIPTION
**Pull request by brandonchinn178**
While investigating #282, I was thinking that Template Haskell might not be great for either GHCJS or the new GHC javascript backend. Plus, Template Haskell is not easily auditable, is difficult to understand, and the code still has a lot of boilerplate (see all the `BijectiveMap` stuff).

Furthermore, if we ever get Fourmolu Live running, I was thinking it'd be cool to move the configuration documentation in the README into the website, and it'd be nice to have one source of truth between the Haskell source code and the website docs.

So I experimented with writing a quick Python script that takes in a YAML file and a Jinja template and generates a Haskell file that's committed to the repo. This is _much_ more auditable, avoids all the negatives of TH, and can generate even more things based off the same YAML file. In this PR, I even had the script generate the in-repo `fourmolu.yaml` file that mimics Ormolu's settings.

### CODE REVIEW

**Comment by brandonchinn178** [comment]
@georgefst I think I really like this new approach, but I'd appreciate a second opinion, in case I overlooked anything. Let me know if you have any concerns!

**Review by georgefst — APPROVED** [review]
I think this is overall a good idea, and solidly executed, even if it isn't quite the approach I'd take personally (see #287).

**Comment by brandonchinn178** [comment]
@georgefst reimplemented with Haskell. I do like the Python version more, but I don't dislike the Haskell version, and I do agree that it's probably more approachable for contributors.

**Review by georgefst — APPROVED** [review]
Nice work. And kudos for the GHC proposals for interpolation and multi-line strings!

**Pull request merged**
